### ISSUE TITLE
Misspelling of "Hierarchy"

### ISSUE THREAD

**Issue by nsriv** [React-Proto/react-proto#62]
Small issue on a wonderful project: 
react-proto/src/components/RightTabs.jsx, line 93

"Heirarchy" should be "Hierarchy"

Not sure where else it appears, but that was the immediately noticeable typo prevalent in all screenshots.

**Comment by refinedblessing** [comment]
Thanks, @nsriv I will work on a fix now.

**Comment by refinedblessing** [comment]
Fixed
