### ISSUE TITLE
Error in Windows 7

### ISSUE THREAD

**Issue by enieber** [React-Proto/react-proto#65]
I try install in windows 7 but no has success.

I receive this error

<img width="956" alt="sem titulo" src="https://user-images.githubusercontent.com/7907068/44933045-051a7e00-ad3e-11e8-9d17-5a66e20e952f.png">

**Comment by enieber** [comment]
I try install using `React-Proto.Web.Setup.1.0.0.exe` but in windows 7 you need download sorce code and run React-Proto.exe

**Comment by refinedblessing** [comment]
Hi @enieber, were you able to fix the issue. Seems to me like an internet connection but if it wasn't, please do share how you fixed it.
