### ISSUE TITLE
RPM package (Red hat & Fedora users)

### ISSUE THREAD

**Issue by LucasCalazans** [React-Proto/react-proto#72]
Hello guys,

First of all, thank you and congratulations for this project.

I've tried to install using the deb package and converting with alien to rpm but I received an error.

It will be nice to have a native rpm package. Is it possible?

**Comment by refinedblessing** [comment]
Hi @LucasCalazans,
Thanks for raising this issue, did you try using the AppImage format [here](https://github.com/React-Proto/react-proto/releases/download/v1.0.0/react-proto-1.0.0-x86_64.AppImage)?
