### ISSUE TITLE
Download not available for Red Hat based distros

### ISSUE THREAD

**Issue by feat7** [React-Proto/react-proto#77]
Right now, linux download has only .deb file.
It would be good to have .rpm file as well.

**Comment by koolamusic** [comment]
Have you seen this https://github.com/electron-userland/electron-installer-redhat
The app is built with electron and can be packaged in rpm binaries

**Comment by feat7** [comment]
@koolamusic
Yes I have seen and already ran in my fedora. I was suggesting to put that packaged rpm available for download.

**Comment by marcelh89** [comment]
> @koolamusic
On Fedora you could use the react-proto-2.0.0-x86_64.AppImage instead. After download just give execution rights ```chmod +x react-proto-2.0.0-x86_64.AppImage``` and run ```./react-proto-2.0.0-x86_64.AppImage```
