### ISSUE TITLE
Konva.Transformer is currently experimental and may have bugs. 

### ISSUE THREAD

**Issue by meredithpatrick** [React-Proto/react-proto#78]
bundle.js:45 Konva warning: Konva.Transformer is currently experimental and may have bugs. Please report any issues to GitHub repo.
warn @ bundle.js:45

**Comment by refinedblessing** [comment]
Konva is an npm module, react-konva to be more specific that we used, you can check it out [here.](https://github.com/konvajs/react-konva)
